In [47]:
#Dependencies
from matplotlib import pyplot as plt
import pandas as pd
import numpy as np
import sklearn
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.cluster import KMeans
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced

In [48]:
#read csv into df
clean_other_df = pd.read_csv("Cleaned_dataset.csv")
# columns to drop... salary_currency, salary, work_year
clean_other_df.sample(25)

,totalyearlycompensation,yearsofexperience,Masters_Degree,Bachelors_Degree,Doctorate_Degree,company_Amazon,company_Apple,company_Booz Allen Hamilton,company_Capital One,company_Facebook,...,company_Zillow,state_CA,state_DC,state_IL,state_MA,state_NY,state_Other,state_TX,state_VA,state_WA
1686,140000,0.0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
1236,181000,6.0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
2157,190000,0.0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
433,180000,0.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
7,690000,10.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1672,138000,0.0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
565,270000,3.0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1063,220000,1.0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
1813,400000,10.0,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
392,212000,2.0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
748,228000,3.0,0,0,1,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
181,108000,1.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
359,120000,3.0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
249,300000,1.0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1753,370000,9.0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
1872,210000,2.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
2094,564000,9.0,0,0,1,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1156,206000,0.0,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1759,139000,1.0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1096,217000,5.0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1187,175000,0.0,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1126,182000,0.0,0,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1728,194000,3.0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1980,525000,6.0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
835,350000,7.0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0

In [49]:
clean_other_df.corr(method ='pearson')

,totalyearlycompensation,yearsofexperience,Masters_Degree,Bachelors_Degree,Doctorate_Degree,company_Amazon,company_Apple,company_Booz Allen Hamilton,company_Capital One,company_Facebook,...,company_Zillow,state_CA,state_DC,state_IL,state_MA,state_NY,state_Other,state_TX,state_VA,state_WA
totalyearlycompensation,1.000000,0.384883,-0.077670,-0.103190,0.195154,0.056856,0.093511,-0.103209,-0.093686,0.124512,...,-0.004772,0.336568,-0.107276,-0.098890,-0.057273,-0.087437,-0.242046,-0.131694,-0.110839,0.049543
yearsofexperience,0.384883,1.000000,0.021349,-0.020237,-0.005330,0.019176,0.044746,-0.017735,-0.018046,0.016342,...,-0.014622,-0.008457,0.016728,-0.021923,-0.012067,-0.061581,0.042701,-0.028371,-0.008066,0.047357
Masters_Degree,-0.077670,0.021349,1.000000,-0.188774,-0.238420,-0.005280,0.025574,0.005271,0.020578,0.007142,...,-0.032993,-0.032740,0.018126,0.045501,0.001027,0.032338,0.022908,0.046768,0.005897,-0.050967
Bachelors_Degree,-0.103190,-0.020237,-0.188774,1.000000,-0.126861,-0.033018,-0.009439,0.093899,-0.018256,0.036385,...,0.039499,-0.054028,0.007560,0.047088,-0.024885,0.023772,0.027322,0.066049,0.057783,-0.033673
Doctorate_Degree,0.195154,-0.005330,-0.238420,-0.126861,1.000000,0.029602,0.036710,-0.033955,-0.007475,-0.005534,...,-0.003388,0.039510,-0.041266,-0.021007,0.057685,-0.060371,0.009265,-0.037016,0.005783,0.003254
company_Amazon,0.056856,0.019176,-0.005280,-0.033018,0.029602,1.000000,-0.062460,-0.035649,-0.047500,-0.097708,...,-0.032644,-0.167657,-0.046386,-0.049657,-0.008933,-0.035506,-0.090856,-0.057026,-0.023609,0.381930
company_Apple,0.093511,0.044746,0.025574,-0.009439,0.036710,-0.062460,1.000000,-0.019901,-0.026516,-0.054544,...,-0.018223,0.174216,-0.025895,-0.027721,-0.033646,-0.067015,-0.070830,0.056785,-0.025579,-0.087794
company_Booz Allen Hamilton,-0.103209,-0.017735,0.005271,0.093899,-0.033955,-0.035649,-0.019901,1.000000,-0.015134,-0.031131,...,-0.010401,-0.092807,0.329877,-0.015822,-0.019204,-0.038249,0.023852,-0.020710,0.270746,-0.053647
company_Capital One,-0.093686,-0.018046,0.020578,-0.018256,-0.007475,-0.047500,-0.026516,-0.015134,1.000000,-0.041480,...,-0.013858,-0.117140,0.170070,0.001138,-0.025587,0.060695,-0.053865,0.093051,0.364586,-0.071480
company_Facebook,0.124512,0.016342,0.007142,0.036385,-0.005534,-0.097708,-0.054544,-0.031131,-0.041480,1.000000,...,-0.028506,0.139964,-0.028239,-0.031872,-0.052633,0.010665,-0.105767,-0.021107,-0.040013,-0.026506
company_Google,0.100968,0.028065,-0.076167,0.002840,0.059545,-0.065829,-0.036748,-0.020974,-0.027946,-0.057486,...,-0.019206,0.135035,-0.027291,-0.029216,-0.035461,-0.040800,-0.060350,-0.025581,-0.009324,-0.034119
company_IBM,-0.112519,-0.012142,0.004634,0.076078,-0.031252,-0.054711,-0.030542,-0.017432,-0.023226,-0.047777,...,-0.015962,-0.057018,0.039498,0.014548,-0.029472,0.109824,0.057015,0.028456,-0.022405,-0.075310
company_Intel,-0.046649,0.006718,-0.032993,0.005320,0.073569,-0.032644,-0.018223,-0.010401,-0.013858,-0.028506,...,-0.009524,-0.075598,-0.013533,-0.014488,-0.017584,-0.035024,0.243261,-0.018964,-0.013368,-0.049124
company_Intuit,0.021191,0.046312,0.017690,-0.032767,-0.013556,-0.037065,-0.020691,-0.011809,-0.015735,-0.032367,...,-0.010814,0.102388,-0.015366,0.011804,-0.019966,-0.039768,-0.029656,0.000384,-0.015179,-0.055777
company_JPMorgan Chase,-0.074428,0.008798,-0.001839,-0.006947,-0.008660,-0.039752,-0.022191,-0.012666,-0.016876,-0.034714,...,-0.011598,-0.103486,-0.016480,-0.017642,-0.021414,0.186441,0.058966,0.038324,-0.016279,-0.059820
company_LinkedIn,0.024209,-0.024479,-0.040960,-0.023358,-0.012989,-0.041659,-0.023256,-0.013273,-0.017686,-0.036379,...,-0.012154,0.143021,-0.017271,-0.018489,-0.022441,-0.044697,-0.047242,-0.024202,-0.017060,-0.062691
company_Lyft,0.125595,-0.027008,-0.032034,0.015515,-0.010423,-0.035649,-0.019901,-0.011358,-0.015134,-0.031131,...,-0.010401,0.079350,-0.014779,-0.015822,0.005223,0.001976,-0.040427,-0.020710,-0.014599,-0.043032
company_Microsoft,0.009222,0.015951,-0.061836,-0.035908,0.006915,-0.105673,-0.058990,-0.033669,-0.044861,-0.092280,...,-0.030830,-0.211942,-0.043810,-0.046899,0.023728,-0.103541,-0.100969,-0.061390,-0.043275,0.491307
company_Netflix,0.291649,0.024054,-0.033426,-0.020236,0.078894,-0.039096,-0.021825,-0.012457,-0.016598,-0.034141,...,-0.011406,0.134223,-0.016208,-0.017351,-0.021061,-0.041948,-0.044336,-0.022713,-0.016011,-0.058834
company_Other,-0.216325,-0.037985,0.065401,0.014530,-0.049210,-0.306234,-0.170951,-0.097571,-0.130005,-0.267422,...,-0.089344,-0.054156,-0.001001,0.124897,0.114125,0.105484,0.210330,0.072571,-0.038203,-0.305868
company_PayPal,-0.012438,-0.006760,0.048338,-0.028858,-0.029040,-0.032644,-0.018223,-0.010401,-0.013858,-0.028506,...,-0.009524,0.093303,-0.013533,0.017506,-0.017584,-0.020408,-0.037018,-0.018964,-0.013368,-0.049124
company_Twitter,0.042836,-0.024221,-0.015326,-0.029544,-0.005259,-0.033419,-0.018656,-0.010648,-0.014187,-0.029184,...,-0.009750,0.078054,-0.013855,-0.014832,-0.018002,-0.035857,0.003187,0.004837,-0.013686,-0.050291
company_Uber,0.091130,-0.020053,0.000949,-0.018614,0.012815,-0.055672,-0.031078,-0.017738,-0.023634,-0.048616,...,-0.016242,0.163124,-0.023080,-0.024708,-0.029990,-0.051008,-0.063133,-0.032343,-0.022799,-0.056150
company_Walmart Labs,0.033620,0.009343,0.034041,-0.022605,-0.021847,-0.041033,-0.022906,-0.013074,-0.017420,-0.035832,...,-0.011971,0.073318,-0.017011,-0.018211,-0.022104,-0.044025,0.043147,-0.023838,-0.016804,-0.052492
company_Zillow,-0.004772,-0.014622,-0.032993,0.039499,-0.003388,-0.032644,-0.018223,-0.010401,-0.013858,-0.028506,...,1.000000,-0.066215,-0.013533,-0.014488,-0.017584,-0.020408,-0.037018,-0.018964,-0.013368,0.159160
state_CA,0.336568,-0.008457,-0.032740,-0.054028,0.039510,-0.167657,0.174216,-0.092807,-0.117140,0.139964,...,-0.066215,1.000000,-0.120758,-0.129274,-0.156907,-0.312523,-0.330314,-0.169218,-0.119285,-0.438332
state_DC,-0.107276,0.016728,0.018126,0.007560,-0.041266,-0.046386,-0.025895,0.329877,0.170070,-0.028239,...,-0.013533,-0.120758,1.000000,-0.020587,-0.024988,-0.049769,-0.052602,-0.026948,-0.018996,-0.069804
state_IL,-0.098890,-0.021923,0.045501,0.047088,-0.021007,-0.049657,-0.027721,-0.015822,0.001138,-0.031872,...,-0.014488,-0.129274,-0.020587,1.000000,-0.026750,-0.053279,-0.056312,-0.028848,-0.020336,-0.074727
state_MA,-0.057273,-0.012067,0.001027,-0.024885,0.057685,-0.008933,-0.033646,-0.019204,-0.025587,-0.052633,...,-0.017584,-0.156907,-0.024988,-0.026750,1.000000,-0.064668,-0.068349,-0.035015,-0.024683,-0.090700
state_NY,-0.087437,-0.061581,0.032338,0.023772,-0.060371,-0.035506,-0.067015,-0.038249,0.060695,0.010665,...,-0.020408,-0.312523,-0.049769,-0.053279,-0.064668,1.000000,-0.136135,-0.069742,-0.049162,-0.180654
state_Other,-0.242046,0.042701,0.022908,0.027322,0.009265,-0.090856,-0.070830,0.023852,-0.053865,-0.105767,...,-0.037018,-0.330314,-0.052602,-0.056312,-0.068349,-0.136135,1.000000,-0.073712,-0.051961,-0.190938
state_TX,-0.131694,-0.028371,0.046768,0.066049,-0.037016,-0.057026,0.056785,-0.020710,0.093051,-0.021107,...,-0.018964,-0.169218,-0.026948,-0.028848,-0.035015,-0.069742,-0.073712,1.000000,-0.026619,-0.097817
state_VA,-0.110839,-0.008066,0.005897,0.057783,0.005783,-0.023609,-0.025579,0.270746,0.364586,-0.040013,...,-0.013368,-0.119285,-0.018996,-0.020336,-0.024683,-0.049162,-0.051961,-0.026619,1.000000,-0.068953
state_WA,0.049543,0.047357,-0.050967,-0.033673,0.003254,0.381930,-0.087794,-0.053647,-0.071480,-0.026506,...,0.159160,-0.438332,-0.069804,-0.074727,-0.090700,-0.180654,-0.190938,-0.097817,-0.068953,1.000000

In [50]:
clean_other_df.corr(method ='kendall')
# between .10 and .29 represent a small association, 
#coefficients between .30 and .49 represent a medium association, 
#coefficients of .50

,totalyearlycompensation,yearsofexperience,Masters_Degree,Bachelors_Degree,Doctorate_Degree,company_Amazon,company_Apple,company_Booz Allen Hamilton,company_Capital One,company_Facebook,...,company_Zillow,state_CA,state_DC,state_IL,state_MA,state_NY,state_Other,state_TX,state_VA,state_WA
totalyearlycompensation,1.000000,0.294166,-0.069762,-0.095127,0.170405,0.081481,0.104330,-0.114728,-0.100134,0.146549,...,0.011713,0.329667,-0.116657,-0.113757,-0.057675,-0.084425,-0.244771,-0.138639,-0.118682,0.072512
yearsofexperience,0.294166,1.000000,0.026833,-0.025244,-0.022686,0.029997,0.056599,-0.011800,-0.022373,0.017763,...,-0.002138,0.008810,0.008624,-0.029496,-0.011554,-0.063661,0.026249,-0.029778,-0.005570,0.046376
Masters_Degree,-0.069762,0.026833,1.000000,-0.188774,-0.238420,-0.005280,0.025574,0.005271,0.020578,0.007142,...,-0.032993,-0.032740,0.018126,0.045501,0.001027,0.032338,0.022908,0.046768,0.005897,-0.050967
Bachelors_Degree,-0.095127,-0.025244,-0.188774,1.000000,-0.126861,-0.033018,-0.009439,0.093899,-0.018256,0.036385,...,0.039499,-0.054028,0.007560,0.047088,-0.024885,0.023772,0.027322,0.066049,0.057783,-0.033673
Doctorate_Degree,0.170405,-0.022686,-0.238420,-0.126861,1.000000,0.029602,0.036710,-0.033955,-0.007475,-0.005534,...,-0.003388,0.039510,-0.041266,-0.021007,0.057685,-0.060371,0.009265,-0.037016,0.005783,0.003254
company_Amazon,0.081481,0.029997,-0.005280,-0.033018,0.029602,1.000000,-0.062460,-0.035649,-0.047500,-0.097708,...,-0.032644,-0.167657,-0.046386,-0.049657,-0.008933,-0.035506,-0.090856,-0.057026,-0.023609,0.381930
company_Apple,0.104330,0.056599,0.025574,-0.009439,0.036710,-0.062460,1.000000,-0.019901,-0.026516,-0.054544,...,-0.018223,0.174216,-0.025895,-0.027721,-0.033646,-0.067015,-0.070830,0.056785,-0.025579,-0.087794
company_Booz Allen Hamilton,-0.114728,-0.011800,0.005271,0.093899,-0.033955,-0.035649,-0.019901,1.000000,-0.015134,-0.031131,...,-0.010401,-0.092807,0.329877,-0.015822,-0.019204,-0.038249,0.023852,-0.020710,0.270746,-0.053647
company_Capital One,-0.100134,-0.022373,0.020578,-0.018256,-0.007475,-0.047500,-0.026516,-0.015134,1.000000,-0.041480,...,-0.013858,-0.117140,0.170070,0.001138,-0.025587,0.060695,-0.053865,0.093051,0.364586,-0.071480
company_Facebook,0.146549,0.017763,0.007142,0.036385,-0.005534,-0.097708,-0.054544,-0.031131,-0.041480,1.000000,...,-0.028506,0.139964,-0.028239,-0.031872,-0.052633,0.010665,-0.105767,-0.021107,-0.040013,-0.026506
company_Google,0.095094,0.018407,-0.076167,0.002840,0.059545,-0.065829,-0.036748,-0.020974,-0.027946,-0.057486,...,-0.019206,0.135035,-0.027291,-0.029216,-0.035461,-0.040800,-0.060350,-0.025581,-0.009324,-0.034119
company_IBM,-0.120135,-0.021665,0.004634,0.076078,-0.031252,-0.054711,-0.030542,-0.017432,-0.023226,-0.047777,...,-0.015962,-0.057018,0.039498,0.014548,-0.029472,0.109824,0.057015,0.028456,-0.022405,-0.075310
company_Intel,-0.045608,0.008541,-0.032993,0.005320,0.073569,-0.032644,-0.018223,-0.010401,-0.013858,-0.028506,...,-0.009524,-0.075598,-0.013533,-0.014488,-0.017584,-0.035024,0.243261,-0.018964,-0.013368,-0.049124
company_Intuit,0.037858,0.045221,0.017690,-0.032767,-0.013556,-0.037065,-0.020691,-0.011809,-0.015735,-0.032367,...,-0.010814,0.102388,-0.015366,0.011804,-0.019966,-0.039768,-0.029656,0.000384,-0.015179,-0.055777
company_JPMorgan Chase,-0.078131,-0.021756,-0.001839,-0.006947,-0.008660,-0.039752,-0.022191,-0.012666,-0.016876,-0.034714,...,-0.011598,-0.103486,-0.016480,-0.017642,-0.021414,0.186441,0.058966,0.038324,-0.016279,-0.059820
company_LinkedIn,0.057052,-0.006642,-0.040960,-0.023358,-0.012989,-0.041659,-0.023256,-0.013273,-0.017686,-0.036379,...,-0.012154,0.143021,-0.017271,-0.018489,-0.022441,-0.044697,-0.047242,-0.024202,-0.017060,-0.062691
company_Lyft,0.089527,-0.017148,-0.032034,0.015515,-0.010423,-0.035649,-0.019901,-0.011358,-0.015134,-0.031131,...,-0.010401,0.079350,-0.014779,-0.015822,0.005223,0.001976,-0.040427,-0.020710,-0.014599,-0.043032
company_Microsoft,0.041657,-0.004600,-0.061836,-0.035908,0.006915,-0.105673,-0.058990,-0.033669,-0.044861,-0.092280,...,-0.030830,-0.211942,-0.043810,-0.046899,0.023728,-0.103541,-0.100969,-0.061390,-0.043275,0.491307
company_Netflix,0.153079,0.030487,-0.033426,-0.020236,0.078894,-0.039096,-0.021825,-0.012457,-0.016598,-0.034141,...,-0.011406,0.134223,-0.016208,-0.017351,-0.021061,-0.041948,-0.044336,-0.022713,-0.016011,-0.058834
company_Other,-0.240956,-0.036937,0.065401,0.014530,-0.049210,-0.306234,-0.170951,-0.097571,-0.130005,-0.267422,...,-0.089344,-0.054156,-0.001001,0.124897,0.114125,0.105484,0.210330,0.072571,-0.038203,-0.305868
company_PayPal,0.004194,0.004148,0.048338,-0.028858,-0.029040,-0.032644,-0.018223,-0.010401,-0.013858,-0.028506,...,-0.009524,0.093303,-0.013533,0.017506,-0.017584,-0.020408,-0.037018,-0.018964,-0.013368,-0.049124
company_Twitter,0.054058,-0.022730,-0.015326,-0.029544,-0.005259,-0.033419,-0.018656,-0.010648,-0.014187,-0.029184,...,-0.009750,0.078054,-0.013855,-0.014832,-0.018002,-0.035857,0.003187,0.004837,-0.013686,-0.050291
company_Uber,0.093531,-0.025273,0.000949,-0.018614,0.012815,-0.055672,-0.031078,-0.017738,-0.023634,-0.048616,...,-0.016242,0.163124,-0.023080,-0.024708,-0.029990,-0.051008,-0.063133,-0.032343,-0.022799,-0.056150
company_Walmart Labs,0.047328,0.016960,0.034041,-0.022605,-0.021847,-0.041033,-0.022906,-0.013074,-0.017420,-0.035832,...,-0.011971,0.073318,-0.017011,-0.018211,-0.022104,-0.044025,0.043147,-0.023838,-0.016804,-0.052492
company_Zillow,0.011713,-0.002138,-0.032993,0.039499,-0.003388,-0.032644,-0.018223,-0.010401,-0.013858,-0.028506,...,1.000000,-0.066215,-0.013533,-0.014488,-0.017584,-0.020408,-0.037018,-0.018964,-0.013368,0.159160
state_CA,0.329667,0.008810,-0.032740,-0.054028,0.039510,-0.167657,0.174216,-0.092807,-0.117140,0.139964,...,-0.066215,1.000000,-0.120758,-0.129274,-0.156907,-0.312523,-0.330314,-0.169218,-0.119285,-0.438332
state_DC,-0.116657,0.008624,0.018126,0.007560,-0.041266,-0.046386,-0.025895,0.329877,0.170070,-0.028239,...,-0.013533,-0.120758,1.000000,-0.020587,-0.024988,-0.049769,-0.052602,-0.026948,-0.018996,-0.069804
state_IL,-0.113757,-0.029496,0.045501,0.047088,-0.021007,-0.049657,-0.027721,-0.015822,0.001138,-0.031872,...,-0.014488,-0.129274,-0.020587,1.000000,-0.026750,-0.053279,-0.056312,-0.028848,-0.020336,-0.074727
state_MA,-0.057675,-0.011554,0.001027,-0.024885,0.057685,-0.008933,-0.033646,-0.019204,-0.025587,-0.052633,...,-0.017584,-0.156907,-0.024988,-0.026750,1.000000,-0.064668,-0.068349,-0.035015,-0.024683,-0.090700
state_NY,-0.084425,-0.063661,0.032338,0.023772,-0.060371,-0.035506,-0.067015,-0.038249,0.060695,0.010665,...,-0.020408,-0.312523,-0.049769,-0.053279,-0.064668,1.000000,-0.136135,-0.069742,-0.049162,-0.180654
state_Other,-0.244771,0.026249,0.022908,0.027322,0.009265,-0.090856,-0.070830,0.023852,-0.053865,-0.105767,...,-0.037018,-0.330314,-0.052602,-0.056312,-0.068349,-0.136135,1.000000,-0.073712,-0.051961,-0.190938
state_TX,-0.138639,-0.029778,0.046768,0.066049,-0.037016,-0.057026,0.056785,-0.020710,0.093051,-0.021107,...,-0.018964,-0.169218,-0.026948,-0.028848,-0.035015,-0.069742,-0.073712,1.000000,-0.026619,-0.097817
state_VA,-0.118682,-0.005570,0.005897,0.057783,0.005783,-0.023609,-0.025579,0.270746,0.364586,-0.040013,...,-0.013368,-0.119285,-0.018996,-0.020336,-0.024683,-0.049162,-0.051961,-0.026619,1.000000,-0.068953
state_WA,0.072512,0.046376,-0.050967,-0.033673,0.003254,0.381930,-0.087794,-0.053647,-0.071480,-0.026506,...,0.159160,-0.438332,-0.069804,-0.074727,-0.090700,-0.180654,-0.190938,-0.097817,-0.068953,1.000000

In [51]:
# #skip procedural encoding with get_dummies()?
# # clean_dummies = clean_dummies.drop(['gender_2'], axis=1)
# clean_dummies = pd.get_dummies(data=clean_bins_df, columns=['company', 'state', 'city'], drop_first=True)#drop the gender columns?
# clean_dummies.head(15)

In [52]:
# #OneHot to new categories
# from sklearn.preprocessing import OneHotEncoder
# enc = OneHotEncoder(sparse=False)
# company_encoded = lb_make.fit_transform(clean_bins2['company'])
# company_encoded = company_encoded.reshape(len(company_encoded), 1)
# onehot_company_encoded = enc.fit_transform(company_encoded)
# print(onehot_company_encoded)

In [53]:
X = clean_other_df.drop(columns=["totalyearlycompensation"])
y = clean_other_df["totalyearlycompensation"]
X.shape
# Scale the dataset using MinMaxScaler()
X_scaled = MinMaxScaler().fit_transform(X)
X_scaled

array([[0.11764706, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.32352941, 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ],
       [0.29411765, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.23529412, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.64705882, 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ],
       [0.17647059, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [54]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_scaled, 
                                                    y, 
                                                    random_state=42)

In [55]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

# Fitting our model with all our features in X
model.fit(X_train, y_train)
training_score = model.score(X_train, y_train)
testing_score = model.score(X_test, y_test)


print(f"Training Score: {training_score}")
print(f"Testing Score: {testing_score}")

Training Score: 0.45084346920994334
Testing Score: 0.4341445923660783

In [56]:
#LinReg basically could not do better than true random... testing random Forest Regressor
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    random_state=42)

In [57]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.datasets import make_regression
# Fitting Random Forest Regression to the dataset
# import the regressor
from sklearn.ensemble import RandomForestRegressor
 
 # create regressor object
regressor = RandomForestRegressor(n_estimators = 100, random_state = 42)
 
# fit the regressor with x and y data
regressor.fit(X, y)

RandomForestRegressor(random_state=42)

In [69]:
uesr_input = pd.read_csv("userinput.csv")
uesr_input

,yearsofexperience,Masters_Degree,Bachelors_Degree,Doctorate_Degree,company_Amazon,company_Apple,company_Booz Allen Hamilton,company_Capital One,company_Facebook,company_Google,...,company_Zillow,state_CA,state_DC,state_IL,state_MA,state_NY,state_Other,state_TX,state_VA,state_WA
0,3,1,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0

In [71]:
uesr_input = pd.read_csv("userinput.csv")
uesr_input

,yearsofexperience,Masters_Degree,Bachelors_Degree,Doctorate_Degree,company_Amazon,company_Apple,company_Booz Allen Hamilton,company_Capital One,company_Facebook,company_Google,...,company_Zillow,state_CA,state_DC,state_IL,state_MA,state_NY,state_Other,state_TX,state_VA,state_WA
0,0,1,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0

In [72]:
Y_pred = regressor.predict(uesr_input)  # test the output by changing values
Y_pred

array([201138.16666667])

In [70]:
Y_pred = regressor.predict(uesr_input)  # test the output by changing values
Y_pred

array([244527.25396825])

In [64]:
uesr_input=X_test.head(1)
uesr_input

,yearsofexperience,Masters_Degree,Bachelors_Degree,Doctorate_Degree,company_Amazon,company_Apple,company_Booz Allen Hamilton,company_Capital One,company_Facebook,company_Google,...,company_Zillow,state_CA,state_DC,state_IL,state_MA,state_NY,state_Other,state_TX,state_VA,state_WA
56,0.0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0

In [65]:
uesr_input.to_csv("userinput.csv", sep=',', header=True, encoding='utf-8', index=False)

In [59]:
training_score = regressor.score(X_train, y_train)
testing_score = regressor.score(X_test, y_test)


print(f"Training Score: {training_score}")
print(f"Testing Score: {testing_score}")

Training Score: 0.7072819990118002
Testing Score: 0.7304247214011321

In [ ]:
# RFR model looks pretty good... 
#could we use cross validation and/or decision trees to determine which features are not contributing to the model
#then tune by removing these noise contributors